fossology/LicenseDb

.github/workflows/go.yml, pkg/authenticate/doc.go, pkg/models/doc.go, pkg/models/types.go
- go 1.18 has reached end of life, use go 1.20
- fix formatting errors
Signed-off-by: Avinal Kumar <avinal.xlvii@gmail.com>
=> chore: add go format check and update go version

cmd/laas/main.go, pkg/api/api.go, pkg/auth/auth.go, pkg/auth/doc.go, pkg/models/types.go
feat: added authentication in API and search api
* Get license with specific search term:
* field: represents the name of field to be searched
* search_term: represents the term to be searched
*  search: represent the algorithm to search with
* authenticate the API:
* added the struct for user  
*  created a user table in the database 
*  added basic user endpoints:
* get user using id 
* get all user
* create user
* added basic authentication to all the API endpoints i.e, group of endpoints
=> feat: added authentication in API and search endpoint

cmd/laas/main.go, go.mod, pkg/api/api.go, pkg/api/api_test.go, pkg/auth/auth.go, pkg/db/db.go, pkg/models/types.go, pkg/utils/util.go
* updated project structure to avoid import cycle
*  added a different package for database where:
* there is function related to migration of database
* and populating database
* added basic test cases:
* added API test cases for create, update, get license by shortname and search in licenses
* added user test cases for create and get user by id
* updated meta to pagination meta for better discription
=> feat: updated project structure and added basic test cases to project

.gitignore, cmd/laas/main.go, pkg/api/api.go, pkg/api/api_test.go, pkg/auth/auth.go, pkg/models/types.go
feat: added audit and change history endpoints.
- /api/audit: to get all the change logs
- /api/audit/:audit_id: to get the change log by its id
- /api/audit/:audit_id/changes: to get all the change history of a particular change log
- /api/audit/:audit_id/changes/:id: to get change of a particular change history
=> feat: created audit and added change history.

cmd/laas/main.go, pkg/api/api.go, pkg/api/api_test.go, pkg/auth/auth.go, pkg/models/types.go
feat: added obligation endpoints.       
-  POST Method "/api/obligations" -create an obligation and its Map    
- DELETE Method "/api/obligations/:topic" -Delete an obligation by its topic and its Map      
- PATCH Method "/api/obligations/:topic" -Update an obligation by its topic   
- GET Method "/api/obligations" -Get all the obligations    
- GET Method "/api/obligations/:topic" -Get an obligation by its topic
=> feat: added obligation endpoints

cmd/laas/docs/docs.go, cmd/laas/docs/swagger.json, cmd/laas/docs/swagger.yaml, pkg/api/api.go
Add `/health` endpoint to inform about DB connectivity.
=> feat(api): add /health endpoint

pkg/auth/auth.go
This PR solves the nil pointer dereference issue(internal server error) highlighted in #28 
In the authentication middleware, the `err` variable is used inconsistently. Please refer to the snippet below- 
https://github.com/fossology/LicenseDb/blob/aa42310676d7cf70a3319d11624bc74dc29372b8/pkg/auth/auth.go#L194-L207
Here the `err` variable is appropriately used to capture potential errors during the base64 decoding process, but it is incorrectly used further in the code. 
https://github.com/fossology/LicenseDb/blob/aa42310676d7cf70a3319d11624bc74dc29372b8/pkg/auth/auth.go#L219-L247
At line 224, `err.Error()` references to decoding errors but it should be referencing to the errors occurring during GORM db querying process happening at line 219. Hence it is replaced by `result.Error.Error()` …
=> fix(api): fixed error handeling in authentication middleware

pkg/api/licenses.go, pkg/api/obligations.go
Fix the `FirstOrCreate()` call in obligation creation endpoint by adding the `Where` clause to check topic and md5. This actually checks if the obligation is a duplicate instead of simply taking the first value.
=> fix(obligation): fix FirstOrCreate in obligation creation

.env, .env.example, .gitignore, README.md, cmd/laas/docs/docs.go, cmd/laas/docs/swagger.json, cmd/laas/docs/swagger.yaml, cmd/laas/main.go, go.mod, go.sum, pkg/api/api.go, pkg/api/audit.go, pkg/api/licenses.go, pkg/api/obligationmap.go, pkg/api/obligations.go, pkg/auth/auth.go, pkg/models/types.go, pkg/utils/util.go
Change the authentication flow of the application.
1. Use `bcrypt` to encrypt the passwords in DB.
2. New endpoint `/login` to generate JWT tokens for authentication.
3. Use JWT tokens in `Authorization` header for authenticating user.
Closes #1
=> feat(auth): use JWT tokens

cmd/laas/main.go, pkg/api/api_test.go, pkg/api/licenses.go, pkg/api/obligations.go
This PR fixes all the errors and warnings cached by `golangci-lint` , hence making the codebase clean and ready to deploy golang static checks and linting action as mentioned in #36 
closes #37 
merge before #36 
CC @GMishx
=> fix(lint): Fixed golang linting errors

.github/workflows/golangci.yml
Added Github Workflow for Golang static checks and linting
completes #33 
Note: To be merged once the codebase is error-free. following are the current errors:
Merge after #38 
CC @avinal @GMishx
=> feat(ci): Github Workflow for Golang static checks and linting

cmd/laas/docs/docs.go, cmd/laas/docs/swagger.json, cmd/laas/docs/swagger.yaml, pkg/api/api.go
This PR makes port in swagger docs configurable. Fetches the env variable "PORT" and assigns it to the swagger config variable "Host" on start.
=> Make port in swagger docs configurable

cmd/laas/docs/docs.go, cmd/laas/docs/swagger.json, cmd/laas/docs/swagger.yaml, pkg/api/obligations.go, pkg/models/optional_data_types.go, pkg/models/types.go
When we unmarshal json, the undefined keys take zero values in structs. So, there is no way to differentiate between an undefined value and an actual zero value when it is passed in json in a PATCH request.
Example: 
{
"active": false,
"text": "Lorem ipsum"
} 
and 
{
"text": "Lorem ipsum"
} 
Structs of both these unmarshalled json objects will have active as false.
=> fix(patch_obligation): Fix patch request bugs in obligation

cmd/laas/docs/docs.go, cmd/laas/docs/swagger.json, cmd/laas/docs/swagger.yaml, pkg/api/licenses.go, pkg/models/types.go
Resolves the following:
1. When we unmarshal json, the undefined keys take zero values in structs. So, there is no way to differentiate between an undefined value and an actual zero value when it is passed in json in a PATCH request.
Example:
{
"active": false,
"text": "Lorem ipsum"
}
and
{
"text": "Lorem ipsum"
}
Structs of both these unmarshalled json objects will have active as false.
2. Also, updates with struct having fields as null values won't be considered for update in database.
=> fix(license_patch): Fix bug in license patch request

cmd/laas/docs/docs.go, cmd/laas/docs/swagger.json, cmd/laas/docs/swagger.yaml, pkg/models/types.go
=> fix(docs): Fix errors in compilation of docs of struct LicensePATCHRequestJSONSchema

cmd/laas/docs/docs.go, cmd/laas/docs/swagger.json, cmd/laas/docs/swagger.yaml, pkg/api/api.go, pkg/api/obligations.go, pkg/models/types.go
=> feat(obligations_export): Add functionality to export obligations

cmd/laas/docs/docs.go, cmd/laas/docs/swagger.json, cmd/laas/docs/swagger.yaml, pkg/api/api.go, pkg/api/licenses.go, pkg/models/optional_data_types.go, pkg/models/types.go
- Made a generic function  `InsertOrUpdateLicenseOnImport` for creating/updating a single license on import. This function will be used in both `Populatedb` function and */licenses/import* endpoint. 
-`InsertOrUpdateLicenseOnImport` takes input a *map* of license fields. This was done to accomodate updates of fields with zero values as valid values( ex. Risk can be 0, Active can be false ). GORM doesn't update fields with zero values when updating using a struct.
- Logic of `addChangelogsForLicenseUpdate` was kept seperate from `InsertOrUpdateLicenseOnImport` to make the latter generic. `Populatedb` won't need `addChangelogsForLicenseUpdate`.
- A new template datatype `NullableAndOptionalData` was introduced to differentiate between fields with zero values and fields with null …
=> feat(license_import): Add endpoint to import licenses via a json file

cmd/laas/docs/docs.go, cmd/laas/docs/swagger.json, cmd/laas/docs/swagger.yaml, pkg/api/api.go, pkg/api/licenses.go, pkg/models/types.go
=> Feat: Add /export endpoint, To export All License Json

pkg/api/licenses.go
Check first if the given column name exists before running the search. It prevents SQL injection.
https://github.com/fossology/LicenseDb/security/code-scanning/3
=> fix(search): check column name before searching

pkg/api/obligationmap.go
- Added error handling and transactions whereever required.
- Seperated the logic of calculating diff from the obligation maps list in database and the list provided by the user to determine the licenses to be inserted and the licenses to be removed into function `GenerateDiffOfLicenses`. 
- Made `PerformObligationMapActions` a global function.
- `PerformObligationMapActions` and `GenerateDiffOfLicenses` can be reused in `ImportObligations` function.
=> refactor(obligation_maps): Add transactions and refactor code

Dockerfile, docker-compose.yml, entrypoint.sh
1. Dockerfile --> Multi Build stage for LicenseDB application
2. docker-compose.yml --> Orchestrate Postgres and Application (LicenseDB)
To Test:
```
docker compose build
docker compose up -d 
```
Closes #63
=> Feat: Docker Support for license DB

pkg/api/licenses.go
- Orders get license response by shortname.
=> fix(license_list): Order licenses by shortname

pkg/auth/auth.go, pkg/middleware/middleware.go, pkg/models/types.go
- Add user information in jwt for showing UI according to user permission level
=> fix(jwt): Add user information in jwt for showing UI according to user permission level

cmd/laas/docs/docs.go, cmd/laas/docs/swagger.json, cmd/laas/docs/swagger.yaml, pkg/api/api.go, pkg/api/obligations.go, pkg/models/types.go
- Create an endpoint to fetch topic and type of all obligations. This data will be displayed as options in the multiselect input which adds obligations to a license.
=> feat(obligations_preview): Create an endpoint to fetch topic and type of all obligations

cmd/laas/docs/docs.go, cmd/laas/docs/swagger.json, cmd/laas/docs/swagger.yaml, pkg/api/obligationmap.go, pkg/models/types.go
- Add type field to reponse of /obligation_maps/license/{license}. It is needed for display in UI.
=> fix(license_obligations): Add type field to response

cmd/laas/docs/docs.go, cmd/laas/docs/swagger.json, cmd/laas/docs/swagger.yaml, pkg/api/api.go, pkg/api/licenses.go, pkg/models/types.go
-  Create an endpoint to fetch shortnames of all licenses. This data will be displayed as options in the multiselect input which adds licenses to a obligation.
=> feat(license_preview): Created an endpoint to fetch all license shortnames

pkg/middleware/middleware.go
Expose the header content-disposition to the browser so that we can access the filename coming from backend.
- Added content-disposition to Access-Control-Expose-Headers.
=> fix(content_disposition): Expose header content-disposition to the browser

cmd/laas/docs/docs.go, cmd/laas/docs/swagger.json, cmd/laas/docs/swagger.yaml, pkg/api/licenses.go, pkg/models/types.go
- Remove unnecessary UpdateExternalRefsJSONPayload type
=> refactor(external_ref): Remove unnecessary UpdateExternalRefsJSONPayload type

cmd/laas/docs/docs.go, cmd/laas/docs/swagger.json, cmd/laas/docs/swagger.yaml, pkg/api/licenses.go
- Enable license sorting by spdx_id, fullname and shortname.
=> feat(license_sorting): Enable sorting in licenses by spdx_id, fullname and shortname

cmd/laas/docs/docs.go, cmd/laas/docs/swagger.json, cmd/laas/docs/swagger.yaml, pkg/api/audit.go, pkg/api/licenses.go, pkg/auth/auth.go, pkg/models/types.go
- Adds field 'entity' and 'user' to the Audit Response. Entity can be of type License or Obligation.
- Removes password from user responses
-  Refactor to remove redundant JWTUser struct
=> Add license/obligation and user data to audit json response

cmd/laas/docs/docs.go, cmd/laas/docs/swagger.json, cmd/laas/docs/swagger.yaml, pkg/api/licenses.go, pkg/models/types.go, pkg/utils/util.go
- Remove rf prefix from license fields in json
=> fix(rf): Remove rf prefix from license fields in json

cmd/laas/docs/docs.go, cmd/laas/docs/swagger.json, cmd/laas/docs/swagger.yaml, pkg/api/api.go, pkg/api/obligationTypes.go, pkg/api/obligations.go, pkg/models/types.go, pkg/utils/util.go
- Added admin APIs to create, delete and get a list of obligation types.
- POST /obligations/types: Creates a new obligation type if not already present. It must be non-empty and uppercase. If the obligation type to be created is already in db with 'active' flag set to false, it is changed to true. 
- DELETE /obligation/types/{type}: The {type} is soft-deleted if it exists in db, has 'active' flag set to true and no obligation references it.
- GET /obligations/types: Fetches a list of all obligation types. Flag 'active' can be set to false to fetch the inactive types.
- During obligation creation and updation, associate them with only active obligation types.
=> feat(admin_obligation_types): Admin apis to create, delete and get obligation types

cmd/laas/docs/docs.go, cmd/laas/docs/swagger.json, cmd/laas/docs/swagger.yaml, pkg/api/api.go, pkg/api/obligationClassifications.go, pkg/api/obligationTypes.go, pkg/models/types.go, pkg/utils/util.go
- Added admin APIs to create, delete and get a list of obligation classifications.
- POST /obligations/classifications: Creates a new obligation classification if not already present. It must be non-empty and uppercase. If the obligation classifications to be created is already in db with 'active' flag set to false, it is changed to true.
- DELETE /obligation/classifications/{classification}: The {classification} is soft-deleted if it exists in db, has 'active' flag set to true and no obligation references it.
- GET /obligations/classifications: Fetches a list of all obligation classifications. Flag 'active' can be set to false to fetch the inactive classifications.
During obligation creation and updation, associate them with only active obligations.
=> feat(obligation_classifications): Add admin apis for creating, listing and deleting obligation classifications

go.mod, go.sum
Upgrade golang.org/x/net/html to 0.33.0 to solve CVE-2024-45338
=> fix(deps): update golang.org/x/net/html

cmd/laas/docs/docs.go, cmd/laas/docs/swagger.json, cmd/laas/docs/swagger.yaml, pkg/api/api.go, pkg/auth/auth.go
- Fetch user profile information for pre-filling user profile update form
=> feat(user_profile): Add endpoint to fetch user profile

cmd/laas/docs/docs.go, cmd/laas/docs/swagger.json, cmd/laas/docs/swagger.yaml, pkg/models/types.go
- Added category field with fixed enums for obligation GET api.
- Updated the obligation POST, PATCH requests accordingly.
- Validation for the new field is also added.
- 
- Fixes #85
=> feat: added new category field in obligations

cmd/laas/docs/docs.go, cmd/laas/docs/swagger.json, cmd/laas/docs/swagger.yaml, pkg/api/api.go, pkg/api/obligationClassifications.go, pkg/api/obligationTypes.go
- The GET obligation types and obligation classifications apis should not be authorized. Only the update, create and delete ones should. These values will be needed in forms for obligation updation/creation.
=> fix(obligation_apis): Make GET obligation classifications and types unauthorized

README.md, cmd/laas/docs/docs.go, cmd/laas/docs/swagger.json, cmd/laas/docs/swagger.yaml, cmd/laas/main.go, pkg/api/api.go, pkg/api/licenses.go, pkg/models/types.go, pkg/utils/util.go
- Added user field as a json object for showing user information.
- Contains userid, username and userlevel.
- Fixes #88
=> feat: added user json as createdBy field in getLicense

cmd/laas/docs/docs.go, cmd/laas/docs/swagger.json, cmd/laas/docs/swagger.yaml, pkg/api/api.go, pkg/api/dashboard.go, pkg/api/licenses.go, pkg/models/types.go
- API for dashboard that returns various statistics such as total licenses count, total obligations count, total users count, license changes since last month and risk-licenses frequency.
=> feat(dashboard): Dashboard api returning different analytics

cmd/laas/docs/docs.go, cmd/laas/docs/swagger.json, cmd/laas/docs/swagger.yaml, pkg/api/licenses.go, pkg/models/types.go
- Swagger documentation was not being detected because of variable declaration before function and after comments for swagger docs.
- The ```validateLicenseFields``` function was called even when the key value for spdx_id in payload was undefined in ```BeforeUpdate``` hook of licenses, causing nil dereference error.
- Closes #109
=> fix(update_license): License update endpoint and it's documentation fixed

cmd/laas/docs/docs.go, cmd/laas/docs/swagger.json, cmd/laas/docs/swagger.yaml, pkg/api/licenses.go, pkg/models/types.go
- Exclude unnecessary fields from the export/get-licenses
- Improve data export format
Closes #111, #112
- Preloaded `USER` in the `export licenses` response.
- Removed `Obligations` from the JSON response.
- Renamed `user` to `created_by` at json response for better readability.
---
- export response 
- get licenses response
After reviewing the full database, this schema is not used directly anywhere. Therefore, these modifications will not introduce breaking changes.  
Additionally, renaming `UserId` to `CreatorId` improves readability for
create-license api and also in database .
=> fix(license_export): optimize schema export for better performance and consistency

Dockerfile
Update Dockerfile to use go version 1.23, the min supported version.
=> fix(docker): update to go 1.23

cmd/laas/docs/docs.go, cmd/laas/docs/swagger.json, cmd/laas/docs/swagger.yaml, pkg/api/obligations.go
- Updated the Swagger documentation to:
- Remove the incorrect 404 response
- Add missing 400 and 500 response documentation to match implementation
- Fixes #119
=> fix(obligations): align Swagger docs with existing implementation for obligations endpoint

cmd/laas/docs/docs.go, cmd/laas/docs/swagger.json, cmd/laas/docs/swagger.yaml, pkg/auth/auth.go, pkg/models/types.go, pkg/utils/util.go
add changelogs for user updates and creation
=> fix(change_logs):add change logs entries for user update/create

cmd/laas/main.go, pkg/api/licenses.go, pkg/api/obligations.go
- due to gorm , the database connection does not use the same connection everytime, it may create another connection(session) before query, where the threshold value is not set(so it gives a result with default 0.3 threshold) ...  so before every connection for similarity search has to set the threshold ..
@deo002
=> fix:similarity api sometimes used the default threshold
